Fix for imgui 1.90 with IMGUI_DISABLE_OBSOLETE_FUNCTIONS
SFML/imgui-sfml pull request #305
Opened 2024-11-13 17:01 UTC by Legulysse

This PR contains fixes for imgui 1.90 when using the IMGUI_DISABLE_OBSOLETE_FUNCTIONS flag.
Associated discussions : https://github.com/SFML/imgui-sfml/issues/301

For this PR to be finalized, the minimum supported version will have to be updated from 1.89 to 1.90.
The supported versions with the flag enabled would range from 1.90 (November 2023) to 1.91.0 (July 2024)

To make the change on the CI settings and docs, I guess I should wait for the imgui_version branch to be merged back into the 2.6.x branch ?

PS: if several tests are implemented for different imgui targets, it could be interesting to also target the -docking tags associated with each imgui version.

2024-11-13 17:18 UTC, Legulysse commented
Oh, it seems that the changes are still compatible with 1.89.
I also just realized that the switch cases I modifed are no longer needed...
I will tweak that.

2024-11-13 22:00 UTC, ChrisThrasher commented
What do we gain by upgrading the minimum ImGui version for ImGui-SFML 2 besides the ability to remove more deprecated functions?

2024-11-15 01:26 UTC, Legulysse commented
Upgrading the minimum version with the associated fixes could allow users to build with the more strict compilation flag, but I realize that maybe we are not many to do that and it's not worth it.
In that case you can wait for deprecation redirectors to disappear from imgui sources before migrating the code and the minimum version, it seems like those breakages are generally trivial to fix.

Concerning this PR, it appears that the changes are still compatible with 1.89, and would allow building with the deprecation flag from 1.89 to 1.91.0.
I will have to test with a gamepad that navigation still works properly.

For more details about API deprecation, I just realized that an exhaustive list exists at the beginning of imgui.cpp (look for "API BREAKING CHANGES" near line 430).

2024-11-15 01:49 UTC, ChrisThrasher commented
> Concerning this PR, it appears that the changes are still compatible with 1.89, and would allow building with the deprecation flag from 1.89 to 1.91.0.

If we can remove the use of interfaces that exist in 1.89 but were deprecated later, I'm cool with that.

2024-11-21 20:55 UTC, ChrisThrasher requested changes

2024-12-01 16:10 UTC, Legulysse commented on imgui-SFML.cpp
> -    // For partial backwards compatibility, also expect some ImGuiNavInput_* values.
Yes they got obsoleted in 1.88.

2024-12-01 16:18 UTC, Legulysse commented on imgui-SFML.cpp
> +    assert(key >= ImGuiKey_NamedKey_BEGIN && key < ImGuiKey_NamedKey_END);
Sure, I just kept it as it was before my edits. I just commited the update.

2024-12-01 16:29 UTC, Legulysse commented
If/When you merge this PR, I invite you to update the imgui_version branch to include the 1.91.5 version tag.

2024-12-06 22:37 UTC, ChrisThrasher approved these changes

2024-12-06 22:37 UTC, merged

2024-12-06 22:37 UTC, ChrisThrasher commented
Thanks!